// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID                 pgtype.UUID        `json:"id"`
	UserChatID         int64              `json:"user_chat_id"`
	Origin             string             `json:"origin"`
	OriginAlternatives []byte             `json:"origin_alternatives"`
	Destination        []byte             `json:"destination"`
	DateFrom           pgtype.Date        `json:"date_from"`
	DateTo             pgtype.Date        `json:"date_to"`
	ReturnDateFrom     pgtype.Date        `json:"return_date_from"`
	ReturnDateTo       pgtype.Date        `json:"return_date_to"`
	TripLengthMin      *int32             `json:"trip_length_min"`
	TripLengthMax      *int32             `json:"trip_length_max"`
	MaxPrice           pgtype.Numeric     `json:"max_price"`
	MaxStops           *int32             `json:"max_stops"`
	MaxDurationMinutes *int32             `json:"max_duration_minutes"`
	AirlinesWhitelist  []byte             `json:"airlines_whitelist"`
	AirlinesBlacklist  []byte             `json:"airlines_blacklist"`
	AlertStrategy      string             `json:"alert_strategy"`
	AlertParams        []byte             `json:"alert_params"`
	CooldownHours      *int32             `json:"cooldown_hours"`
	DryRun             bool               `json:"dry_run"`
	MutedUntil         pgtype.Timestamptz `json:"muted_until"`
	Status             string             `json:"status"`
	NextCheckAt        pgtype.Timestamptz `json:"next_check_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type UserSetting struct {
	ChatID             int64              `json:"chat_id"`
	CooldownHours      *int32             `json:"cooldown_hours"`
	DropPct            *float64           `json:"drop_pct"`
	StablePriceBandPct *float64           `json:"stable_price_band_pct"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
