// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserSetting struct {
	ChatID             int64              `json:"chat_id"`
	CooldownHours      *int32             `json:"cooldown_hours"`
	DropPct            *float64           `json:"drop_pct"`
	StablePriceBandPct *float64           `json:"stable_price_band_pct"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
