// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSubscription = `-- name: CreateSubscription :one

INSERT INTO subscriptions (
    user_chat_id,
    origin, origin_alternatives, destinations,
    date_from, date_to, return_date_from, return_date_to,
    trip_length_min, trip_length_max,
    max_price_minor, max_stops, max_duration_minutes,
    airlines_whitelist, airlines_blacklist,
    alert_strategy, cooldown_hours, drop_pct, stable_price_band_pct,
    muted_until, status
) VALUES (
    $1,
    $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    $11, $12, $13,
    $14, $15,
    $16, $17, $18, $19,
    $20, $21
)
RETURNING id, user_chat_id, origin, origin_alternatives, destinations, date_from, date_to, return_date_from, return_date_to, trip_length_min, trip_length_max, max_price_minor, max_stops, max_duration_minutes, airlines_whitelist, airlines_blacklist, alert_strategy, cooldown_hours, drop_pct, stable_price_band_pct, muted_until, status, next_check_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserChatID         int64      `json:"user_chat_id"`
	Origin             string     `json:"origin"`
	OriginAlternatives []string   `json:"origin_alternatives"`
	Destinations       []string   `json:"destinations"`
	DateFrom           time.Time  `json:"date_from"`
	DateTo             time.Time  `json:"date_to"`
	ReturnDateFrom     *time.Time `json:"return_date_from"`
	ReturnDateTo       *time.Time `json:"return_date_to"`
	TripLengthMin      *int32     `json:"trip_length_min"`
	TripLengthMax      *int32     `json:"trip_length_max"`
	MaxPriceMinor      *int64     `json:"max_price_minor"`
	MaxStops           *int32     `json:"max_stops"`
	MaxDurationMinutes *int32     `json:"max_duration_minutes"`
	AirlinesWhitelist  []string   `json:"airlines_whitelist"`
	AirlinesBlacklist  []string   `json:"airlines_blacklist"`
	AlertStrategy      string     `json:"alert_strategy"`
	CooldownHours      *int32     `json:"cooldown_hours"`
	DropPct            *float64   `json:"drop_pct"`
	StablePriceBandPct *float64   `json:"stable_price_band_pct"`
	MutedUntil         *time.Time `json:"muted_until"`
	Status             string     `json:"status"`
}

// Every query is scoped by user_chat_id: identity comes only from the
// initData middleware, and a foreign id must behave exactly like a missing
// one (the API returns 404, never 403 — no existence oracle).
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserChatID,
		arg.Origin,
		arg.OriginAlternatives,
		arg.Destinations,
		arg.DateFrom,
		arg.DateTo,
		arg.ReturnDateFrom,
		arg.ReturnDateTo,
		arg.TripLengthMin,
		arg.TripLengthMax,
		arg.MaxPriceMinor,
		arg.MaxStops,
		arg.MaxDurationMinutes,
		arg.AirlinesWhitelist,
		arg.AirlinesBlacklist,
		arg.AlertStrategy,
		arg.CooldownHours,
		arg.DropPct,
		arg.StablePriceBandPct,
		arg.MutedUntil,
		arg.Status,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserChatID,
		&i.Origin,
		&i.OriginAlternatives,
		&i.Destinations,
		&i.DateFrom,
		&i.DateTo,
		&i.ReturnDateFrom,
		&i.ReturnDateTo,
		&i.TripLengthMin,
		&i.TripLengthMax,
		&i.MaxPriceMinor,
		&i.MaxStops,
		&i.MaxDurationMinutes,
		&i.AirlinesWhitelist,
		&i.AirlinesBlacklist,
		&i.AlertStrategy,
		&i.CooldownHours,
		&i.DropPct,
		&i.StablePriceBandPct,
		&i.MutedUntil,
		&i.Status,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions
WHERE id = $1 AND user_chat_id = $2
`

type DeleteSubscriptionParams struct {
	ID         string `json:"id"`
	UserChatID int64  `json:"user_chat_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, arg.ID, arg.UserChatID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, user_chat_id, origin, origin_alternatives, destinations, date_from, date_to, return_date_from, return_date_to, trip_length_min, trip_length_max, max_price_minor, max_stops, max_duration_minutes, airlines_whitelist, airlines_blacklist, alert_strategy, cooldown_hours, drop_pct, stable_price_band_pct, muted_until, status, next_check_at, created_at, updated_at FROM subscriptions
WHERE id = $1 AND user_chat_id = $2
`

type GetSubscriptionParams struct {
	ID         string `json:"id"`
	UserChatID int64  `json:"user_chat_id"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.ID, arg.UserChatID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserChatID,
		&i.Origin,
		&i.OriginAlternatives,
		&i.Destinations,
		&i.DateFrom,
		&i.DateTo,
		&i.ReturnDateFrom,
		&i.ReturnDateTo,
		&i.TripLengthMin,
		&i.TripLengthMax,
		&i.MaxPriceMinor,
		&i.MaxStops,
		&i.MaxDurationMinutes,
		&i.AirlinesWhitelist,
		&i.AirlinesBlacklist,
		&i.AlertStrategy,
		&i.CooldownHours,
		&i.DropPct,
		&i.StablePriceBandPct,
		&i.MutedUntil,
		&i.Status,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, user_chat_id, origin, origin_alternatives, destinations, date_from, date_to, return_date_from, return_date_to, trip_length_min, trip_length_max, max_price_minor, max_stops, max_duration_minutes, airlines_whitelist, airlines_blacklist, alert_strategy, cooldown_hours, drop_pct, stable_price_band_pct, muted_until, status, next_check_at, created_at, updated_at FROM subscriptions
WHERE user_chat_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptions(ctx context.Context, userChatID int64) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions, userChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserChatID,
			&i.Origin,
			&i.OriginAlternatives,
			&i.Destinations,
			&i.DateFrom,
			&i.DateTo,
			&i.ReturnDateFrom,
			&i.ReturnDateTo,
			&i.TripLengthMin,
			&i.TripLengthMax,
			&i.MaxPriceMinor,
			&i.MaxStops,
			&i.MaxDurationMinutes,
			&i.AirlinesWhitelist,
			&i.AirlinesBlacklist,
			&i.AlertStrategy,
			&i.CooldownHours,
			&i.DropPct,
			&i.StablePriceBandPct,
			&i.MutedUntil,
			&i.Status,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions SET
    origin                = $3,
    origin_alternatives   = $4,
    destinations          = $5,
    date_from             = $6,
    date_to               = $7,
    return_date_from      = $8,
    return_date_to        = $9,
    trip_length_min       = $10,
    trip_length_max       = $11,
    max_price_minor       = $12,
    max_stops             = $13,
    max_duration_minutes  = $14,
    airlines_whitelist    = $15,
    airlines_blacklist    = $16,
    alert_strategy        = $17,
    cooldown_hours        = $18,
    drop_pct              = $19,
    stable_price_band_pct = $20,
    muted_until           = $21,
    status                = $22,
    updated_at            = now()
WHERE id = $1 AND user_chat_id = $2
RETURNING id, user_chat_id, origin, origin_alternatives, destinations, date_from, date_to, return_date_from, return_date_to, trip_length_min, trip_length_max, max_price_minor, max_stops, max_duration_minutes, airlines_whitelist, airlines_blacklist, alert_strategy, cooldown_hours, drop_pct, stable_price_band_pct, muted_until, status, next_check_at, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID                 string     `json:"id"`
	UserChatID         int64      `json:"user_chat_id"`
	Origin             string     `json:"origin"`
	OriginAlternatives []string   `json:"origin_alternatives"`
	Destinations       []string   `json:"destinations"`
	DateFrom           time.Time  `json:"date_from"`
	DateTo             time.Time  `json:"date_to"`
	ReturnDateFrom     *time.Time `json:"return_date_from"`
	ReturnDateTo       *time.Time `json:"return_date_to"`
	TripLengthMin      *int32     `json:"trip_length_min"`
	TripLengthMax      *int32     `json:"trip_length_max"`
	MaxPriceMinor      *int64     `json:"max_price_minor"`
	MaxStops           *int32     `json:"max_stops"`
	MaxDurationMinutes *int32     `json:"max_duration_minutes"`
	AirlinesWhitelist  []string   `json:"airlines_whitelist"`
	AirlinesBlacklist  []string   `json:"airlines_blacklist"`
	AlertStrategy      string     `json:"alert_strategy"`
	CooldownHours      *int32     `json:"cooldown_hours"`
	DropPct            *float64   `json:"drop_pct"`
	StablePriceBandPct *float64   `json:"stable_price_band_pct"`
	MutedUntil         *time.Time `json:"muted_until"`
	Status             string     `json:"status"`
}

// Full-row update: PATCH merging happens in Go (read -> apply Optional fields
// -> validate -> write), so the query stays a plain SET list instead of the
// set_* flag forest a 20-column partial update would need.
func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.UserChatID,
		arg.Origin,
		arg.OriginAlternatives,
		arg.Destinations,
		arg.DateFrom,
		arg.DateTo,
		arg.ReturnDateFrom,
		arg.ReturnDateTo,
		arg.TripLengthMin,
		arg.TripLengthMax,
		arg.MaxPriceMinor,
		arg.MaxStops,
		arg.MaxDurationMinutes,
		arg.AirlinesWhitelist,
		arg.AirlinesBlacklist,
		arg.AlertStrategy,
		arg.CooldownHours,
		arg.DropPct,
		arg.StablePriceBandPct,
		arg.MutedUntil,
		arg.Status,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserChatID,
		&i.Origin,
		&i.OriginAlternatives,
		&i.Destinations,
		&i.DateFrom,
		&i.DateTo,
		&i.ReturnDateFrom,
		&i.ReturnDateTo,
		&i.TripLengthMin,
		&i.TripLengthMax,
		&i.MaxPriceMinor,
		&i.MaxStops,
		&i.MaxDurationMinutes,
		&i.AirlinesWhitelist,
		&i.AirlinesBlacklist,
		&i.AlertStrategy,
		&i.CooldownHours,
		&i.DropPct,
		&i.StablePriceBandPct,
		&i.MutedUntil,
		&i.Status,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
