// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_settings.sql

package sqlcgen

import (
	"context"
)

const ensureUserSettings = `-- name: EnsureUserSettings :one
INSERT INTO user_settings (chat_id)
VALUES ($1)
ON CONFLICT (chat_id) DO UPDATE SET chat_id = EXCLUDED.chat_id
RETURNING chat_id, cooldown_hours, drop_pct, stable_price_band_pct, updated_at
`

// Lazily creates a default settings row on first access (GET /api/v1/me).
func (q *Queries) EnsureUserSettings(ctx context.Context, chatID int64) (UserSetting, error) {
	row := q.db.QueryRow(ctx, ensureUserSettings, chatID)
	var i UserSetting
	err := row.Scan(
		&i.ChatID,
		&i.CooldownHours,
		&i.DropPct,
		&i.StablePriceBandPct,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT chat_id, cooldown_hours, drop_pct, stable_price_band_pct, updated_at FROM user_settings WHERE chat_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, chatID int64) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, chatID)
	var i UserSetting
	err := row.Scan(
		&i.ChatID,
		&i.CooldownHours,
		&i.DropPct,
		&i.StablePriceBandPct,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
INSERT INTO user_settings (chat_id, cooldown_hours, drop_pct, stable_price_band_pct, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (chat_id) DO UPDATE SET
    cooldown_hours        = CASE WHEN $5::bool THEN excluded.cooldown_hours ELSE user_settings.cooldown_hours END,
    drop_pct              = CASE WHEN $6::bool THEN excluded.drop_pct ELSE user_settings.drop_pct END,
    stable_price_band_pct = CASE WHEN $7::bool THEN excluded.stable_price_band_pct ELSE user_settings.stable_price_band_pct END,
    updated_at            = now()
RETURNING chat_id, cooldown_hours, drop_pct, stable_price_band_pct, updated_at
`

type UpdateUserSettingsParams struct {
	ChatID                int64    `json:"chat_id"`
	CooldownHours         *int32   `json:"cooldown_hours"`
	DropPct               *float64 `json:"drop_pct"`
	StablePriceBandPct    *float64 `json:"stable_price_band_pct"`
	SetCooldownHours      bool     `json:"set_cooldown_hours"`
	SetDropPct            bool     `json:"set_drop_pct"`
	SetStablePriceBandPct bool     `json:"set_stable_price_band_pct"`
}

// PATCH /api/v1/me — true PATCH semantics: each column is written only when its
// set_* flag is true (JSON key present); a true flag with a NULL value clears
// the column back to the cascade default. Flags false → column untouched.
func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.ChatID,
		arg.CooldownHours,
		arg.DropPct,
		arg.StablePriceBandPct,
		arg.SetCooldownHours,
		arg.SetDropPct,
		arg.SetStablePriceBandPct,
	)
	var i UserSetting
	err := row.Scan(
		&i.ChatID,
		&i.CooldownHours,
		&i.DropPct,
		&i.StablePriceBandPct,
		&i.UpdatedAt,
	)
	return i, err
}
